let a = `hello`;
let b = `owu`;
let c = `com`;
let d = `ua`;
let f = 1;
let s = 10;
let e = -999;
let t = 123;
let h = 3.14;
let q = 16;
let j = true;
let l = false;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(f);
console.log(s);
console.log(e);
console.log(t);
console.log(h);
console.log(q);
console.log(j);
console.log(l);